name: tradewatch
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  google_fonts: ^6.3.2
  get_it: ^9.0.5
  badges: ^3.1.2
  flutter_svg: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.10.3
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/
